# https://github.com/tradichel/SecurityMetricsAutomation
# IAM/stacks/User/cfn/Parameter.yaml
# author: @tradichel @2ndsightlab
# description: CloudFormation template to create an SSM Parameter
# NOT TESTED: Because we cannot encrypt parameters, 
# going to create a function that uses the AWS CLI
##############################################################
Parameters:
  NameParam:
    Type: String
  ValueParam:
    Type: String
    Default: "Default"
  DescriptionParam:
    Type: String
    Default: ""
  DataTypeParam:
    Type: String
    Default: "text"
    AllowedValues:
      - "text"
      - "aws:ec2:image"
  TypeParam:
    Type: String
    Default: "String"
    AllowedValues:
      - "String"
      - "StringList"
      #Does not support SecureString at time of writing
      #Added to AWSWishList.com
   TierParam:
    Type: String
    Default: "Standard"
    AllowedValues:
      - "Advanced"
      - "Intelligent-Tiering" 
      - "Standard"
    #Standard parameters, Type: SecureString: < 4096 bytes. Encrypted/decrypted directly w/KMS key you specify.
    #Advanced parameters, Type: SecureString: Envelope encryption w/KMS key you specify 
    AllowedPatternParam:
      Type: String
      Default: !Ref AWS::NoValue
    PoliciesParam:
      Type: String
      Default: !Ref AWS::NoValue
    TagsParam:
      Type: String
      Default: !Ref AWS::NoValue

Resources:
  Paramaeter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref NameParam
      DataType: !Ref DataTypeParam
      SecretString: !Ref SecretValue
      Value: !Ref ValueParam
      Type: !Ref TypeParam 
        #CloudFormation does not support SecureString for Parameter Store
        #which is why parameters are not used for sensitived data
        #in this framework
      AllowedPattern: !Ref AllowedPatternParam
      Policies: !Ref PoliciesParam
      Tier: !Ref TierParam
      Tags: !Ref TagsParam

Outputs:
  ParameterOutput:
    Value: !Ref Parameter
    Export:
     Name: !Sub ${NameParam}ParameterExport

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
