#!/bin/bash -e
# https://github.com/tradichel/SecurityMetricsAutomation
# awsdeploy/resources/secretsmanager/secret/secret.yaml
# author: @teriradichel @2ndsightlab
# Description: deploy a secret
##############################################################
Parameters:
  NameParam:
    Type: String
  KMSKeyID:
    Type: String
  SecretValue:
    Type: String
    Default: "Default"

Resources:
  secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref NameParam
      KmsKeyId: !Ref KMSKeyID
      SecretString: !Ref SecretValue

Outputs:
  secretid:
    Value: !GetAtt secret.Id
    Export:
     Name: !Sub id-secretsmanager-secret-${NameParam}
  secretarn:
    Value: !Ref secret
    Export:
     Name: !Sub arn-secretsmanager-secret-${NameParam}

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################ 
