# https://github.com/tradichel/SecurityMetricsAutomation
# awsdeploy/resources/organizations/resourcepolicy/resourcepolicy.yaml
# author: @tradichel @2ndsightlab
# Organiztaion resource policy that allows other acccounts to
# manage organization resources
##############################################################
Resources:
  ResourcePolicy:
    Type: AWS::Organizations::ResourcePolicy
    Properties:
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: OrgAdminAccountFullAccess
            Effect: Allow
            Principal:
              AWS:
                !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !ImportValue #fixthis-change to governance account
                    - ':root'
            Action:
              - 'organizations:AttachPolicy'
              - 'organizations:CreatePolicy'
              - 'organizations:DeletePolicy'
              - 'organizations:DescribeAccount'
              - 'organizations:DescribeCreateAccountStatus'
              - 'organizations:DescribeEffectivePolicy'
              - 'organizations:DescribeHandshake'
              - 'organizations:DescribeOrganization'
              - 'organizations:DescribeOrganizationalUnit'
              - 'organizations:DescribePolicy'
              - 'organizations:DescribeResourcePolicy'
              - 'organizations:DetachPolicy'
              - 'organizations:DisablePolicyType'
              - 'organizations:EnablePolicyType'
              - 'organizations:ListAccounts'
              - 'organizations:ListAccountsForParent'
              - 'organizations:ListAWSServiceAccessForOrganization'
              - 'organizations:ListChildren'
              - 'organizations:ListCreateAccountStatus'
              - 'organizations:ListDelegatedAdministrators'
              - 'organizations:ListDelegatedServicesForAccount'
              - 'organizations:ListHandshakesForAccount'
              - 'organizations:ListHandshakesForOrganization'
              - 'organizations:ListOrganizationalUnitsForParent'
              - 'organizations:ListParents'
              - 'organizations:ListPolicies'
              - 'organizations:ListPoliciesForTarget'
              - 'organizations:ListRoots'
              - 'organizations:ListTagsForResource'
              - 'organizations:ListTargetsForPolicy'
              - 'organizations:TagResource'
              - 'organizations:UntagResource'
              - 'organizations:UpdatePolicy'
            Resource: '*'

Outputs:
  ResourcePolicyID:
    Value: !Ref ResourcePolicy
    Export:
     Name: !Sub id-organizations-resourcepolicy-${NameParam}
  ResourcePolicyArn:
    Value: !GetAtt ResourcePolicy.Arn
    Export:
     Name: !Sub arn-organizations-resourcepolicy-${NameParam}

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
