# https://github.com/tradichel/SecurityMetricsAutomation
# Org/stacks/S3/cfn/Policy/CloudTrailPolicy.yaml
# author: @tradichel @2ndsightlab
# description: Bucket policy for CloudTrail bucket
##############################################################
Parameters:
  CloudTrailArnParam:
    Type: String
    Default: "*"
  OrganizationIdParam:
    Type: String

Conditions:
   NoCloudTrailArn:
     !Equals 
        - !Ref CloudTrailArnParam
        - "*"

Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue 'BucketName-orgroot-cloudtrail'
      PolicyDocument:
        Statement:
          - Sid: AllowTLSRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !ImportValue BucketArn-orgroot-cloudtrail
              - !Sub 
                  - ${BucketArn}/*
                  - BucketArn: !ImportValue BucketArn-orgroot-cloudtrail
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Sid: GetBucketAcl
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !ImportValue BucketArn-orgroot-cloudtrail
            Condition:
              !If
                - NoCloudTrailArn
                - !Ref AWS::NoValue
                - StringEquals:
                    'aws:SourceArn': !Ref CloudTrailArnParam
          - Sid: WriteToBucket
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource:
              - !Sub
                  - ${BucketArn}/AWSLogs/*
                  - BucketArn: !ImportValue BucketArn-orgroot-cloudtrail
                    OrgId: !Ref OrganizationIdParam          
            Condition:
              !If
                 - NoCloudTrailArn
                 - !Ref AWS::NoValue
                 - 
                    StringEquals:
                      'aws:SourceArn': !Ref CloudTrailArnParam
          - Sid: ListBucket
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:ListBucket
            Resource: !ImportValue BucketArn-orgroot-cloudtrail
          - Sid: GetBucketAcl
            Effect: Allow
            Principal: 
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !ImportValue BucketArn-orgroot-cloudtrail

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
