# https://github.com/tradichel/SecurityMetricsAutomation
# awsdeploy/resources/iam/rolepolicy/rootadminuserrolepolicy.yaml
# author: @tradichel @2ndsightlab
# description: CloudFormation template to delploy an OU
##############################################################
Resources:
  Policy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: root-adminrole
      PolicyName: root-adminrolepolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowAllActions"
            Effect: Allow
            Action: '*'
            Resource: '*'
          - Sid: "DenyTheseActionsInRootAccount"
            Effect: Deny
            Action:
              - iam:AttachUserPolicy
              - iam:AttachGroupPolicy
              - iam:CreateUser
              - iam:DetachUserPolicy
              - iam:DeleteUserPermissionsBoundary
              - iam:PutUserPermissionsBoundary
              - iam:PutUserPolicy
              - iam:Tag*
              - iam:Untag*
              - iam:UpdateUser
              - iam:CreateGroup
              - iam:PassRole
              - iam:CreateInstanceProfile
              - iam:CreateSAML
              - iam:CreateOpenIDConnectProvider
              - iam:PutUserPolicy
              - iam:AddUserToGroup
              - iam:AddRoleToInstanceProfile
              - iam:AddClientIDToOpenIDConnectProvider
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:*'
          - Sid: "AllowCreateRoleWithhPermissionBoundaryInRootAccount"
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:UpdateRole
              - iam:AttachRolePolicy
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:*'
            Condition:
              StringEquals:
                iam:PermissionsBoundary: 'arn:aws:iam::${AWS::AccountId}:policy/root-accountpermissionsboundary'

Outputs:
  PolicyID:
    Value: !Ref Policy
    Export:
     Name: !Sub id-iam-rolepolicy-root-adminrolepolicy
  PolicyArn:
    Value: !Ref Policy
    Export:
     Name: !Sub arn-iam-rolepolicy-root-adminrolepolicyarn

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
