# https://github.com/tradichel/SecurityMetricsAutomation
# awsdeploy/resources/route53/aliasrecord.yaml
# author: @teriradichel @2ndsightlab
##############################################################

AWSTemplateFormatVersion: "2010-09-09"
Description: Point domain name A record to CloudFront

#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-dnshostname

#hosted zone IDs for S3. Good to know.
#https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
Parameters:
  CodeParam:
    Description: Code identifying the web application 
    Type: String
  COGNITOMAGICHOSTEDZONEID:
    Description: Putting this here so I don't forget again. Weird required value.
    Type: String
    AllowedValues:
      - Z2FDTNDATAQYW2
    Default: Z2FDTNDATAQYW2
  
Resources:

  #this a record is to point the domain to the cloudfront distribution
  ContentDomainAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Fn::ImportValue:
          !Sub ${CodeParam}-Content-DomainId
      RecordSets:
      - Name: 
          Fn::ImportValue: 
            !Sub ${CodeParam}-ContentDomain
        Type: A
        AliasTarget:
          #magic cloudfront domain id Z2FDTNDATAQYW2
          HostedZoneId: !Ref COGNITOMAGICHOSTEDZONEID
          DNSName:
            Fn::ImportValue:
              !Sub CloudFrontContentDomain-${CodeParam}


#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################ 
